controller_manager:
  ros__parameters:
    update_rate: 500 # Hz
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    joint_trajectory_controller:
      type: fanuc_controllers/ScaledJointTrajectoryController
    gripper_controller:
      type: position_controllers/GripperActionController
    fanuc_gpio_controller:
      type: fanuc_controllers/FanucGPIOController

joint_trajectory_controller:
  ros__parameters:
    joints:
      - J1
      - J2
      - J3
      - J4
      - J5
      - J6
    command_interfaces:
      - position
    state_interfaces:
      - position
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.0
      goal_time: 0.0

gripper_controller:
  ros__parameters:
    joint: robotiq_85_left_knuckle_joint
    command_interface: position
    state_interface: position

fanuc_gpio_controller:
  ros__parameters:
    gpio_config_file_package: fanuc_hardware_interface
    gpio_config_file_path: config/example_gpio_config.yaml
